<a href="https://colab.research.google.com/github/brunahariadni/Miniprojeto_Bruna_Analise_de_Dados_T6/blob/main/Miniprojeto_Bruna_Analise_de_Dados_T6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mini-Projeto - Análise Exploratória de Dados no Varejo

**Aluna:** Bruna Hariadni
**Turma:** Análise de Dados T6

## Objetivo

Realizar uma Análise Exploratória de Dados da base Varejo, identificando problemas de qualidade, realizando a limpeza dos dados e explorando características e padrões presentes na base.

In [1]:
# Importação e carregamento dos dados
import pandas as pd
df = pd.read_csv("Base Varejo.csv", sep=";")

In [2]:
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [3]:
df.shape

(830000, 14)

In [4]:
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [5]:
df.dtypes

DATA            object
CO_ID            int64
CL_ID            int64
CL_GENERO       object
CL_EC            int64
CL_FHL           int64
CL_SEG          object
PR_ID            int64
PR_CAT          object
PR_NOME         object
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

## 2. Verificação da qualidade dos dados

Nesta etapa serão verificados possíveis problemas na base, como valores nulos, registros duplicados e inconsistências nos dados.

In [6]:
df.isnull().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(96553)

In [8]:
df["PR_CAT"].value_counts()

PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64

In [9]:
df[df.duplicated()].head(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
51,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
77,01/02/2019,1078,290,F,1,0,B,210,ACESSORIOS,CHUPETA,NaN,NaN,NaN,NaN
78,01/02/2019,1078,290,F,1,0,B,99,LIMPEZA,DESINFETANTE,NaN,NaN,NaN,NaN
96,01/02/2019,1078,290,F,1,0,B,144,BEBIDAS,REFRIGERANTE COLA,NaN,NaN,NaN,NaN
97,01/02/2019,1078,290,F,1,0,B,125,HIGIENE,TINTURAS,NaN,NaN,NaN,NaN

## 3. Limpeza e tratamento dos dados

Nesta etapa, serão removidas colunas sem informação útil, tratados valores inconsistentes, eliminadas duplicatas e ajustados os tipos de dados necessários para a análise.

In [10]:
df = df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"])

In [11]:
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME'],
      dtype='object')

In [12]:
df["PR_CAT"] = df["PR_CAT"].replace("#N/D", "Sem Categoria")
df["PR_CAT"].value_counts()

PR_CAT
ALIMENTOS        434767
HIGIENE          155574
LIMPEZA          145754
BEBIDAS           43299
PET               32399
ACESSORIOS        14557
Sem Categoria      3650
Name: count, dtype: int64

In [13]:
linhas_antes = len(df)
df = df.drop_duplicates()
linhas_depois = len(df)
linhas_removidas = linhas_antes - linhas_depois
print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Linhas duplicadas removidas:", linhas_removidas)

Linhas antes: 830000
Linhas depois: 733447
Linhas duplicadas removidas: 96553

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["DATA"].dtype

dtype('O')

In [16]:
df["DATA"].head()

0    01/02/2019
1    01/02/2019
2    01/02/2019
3    01/02/2019
4    01/02/2019
Name: DATA, dtype: object

In [22]:
df["DATA"] = pd.to_datetime(df["DATA"], dayfirst=True)
df["DATA"].dtype

dtype('<M8[ns]')

In [23]:
df["DATA"].head()

0   2019-02-01
1   2019-02-01
2   2019-02-01
3   2019-02-01
4   2019-02-01
Name: DATA, dtype: datetime64[ns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 733447 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       733447 non-null  datetime64[ns]
 1   CO_ID      733447 non-null  int64
 2   CL_ID      733447 non-null  int64
 3   CL_GENERO  733447 non-null  object
 4   CL_EC      733447 non-null  int64
 5   CL_FHL     733447 non-null  int64
 6   CL_SEG     733447 non-null  object
 7   PR_ID      733447 non-null  int64
 8   PR_CAT     733447 non-null  object
 9   PR_NOME    733447 non-null  object
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 61.6+ MB