<a href="https://colab.research.google.com/github/brunahariadni/Miniprojeto_Bruna_Analise_de_Dados_T6/blob/main/Miniprojeto_Bruna_Analise_de_Dados_T6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mini-Projeto - Análise Exploratória de Dados no Varejo

**Aluna:** Bruna Hariadni
**Turma:** Análise de Dados T6

## Objetivo

Realizar uma Análise Exploratória de Dados da base Varejo, identificando problemas de qualidade, realizando a limpeza dos dados e explorando características e padrões presentes na base.

In [5]:
# Importação e carregamento dos dados
import pandas as pd
df = pd.read_csv("Base Varejo.csv", sep=";")

In [6]:
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [7]:
df.shape

(830000, 14)

In [8]:
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [9]:
df.dtypes

DATA            object
CO_ID            int64
CL_ID            int64
CL_GENERO       object
CL_EC            int64
CL_FHL           int64
CL_SEG          object
PR_ID            int64
PR_CAT          object
PR_NOME         object
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

## 2. Verificação da qualidade dos dados

Nesta etapa serão verificados possíveis problemas na base, como valores nulos, registros duplicados e inconsistências nos dados.

In [10]:
df.isnull().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(96553)

In [12]:
df["PR_CAT"].value_counts()

PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64

In [13]:
df[df.duplicated()].head(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
51,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
77,01/02/2019,1078,290,F,1,0,B,210,ACESSORIOS,CHUPETA,NaN,NaN,NaN,NaN
78,01/02/2019,1078,290,F,1,0,B,99,LIMPEZA,DESINFETANTE,NaN,NaN,NaN,NaN
96,01/02/2019,1078,290,F,1,0,B,144,BEBIDAS,REFRIGERANTE COLA,NaN,NaN,NaN,NaN
97,01/02/2019,1078,290,F,1,0,B,125,HIGIENE,TINTURAS,NaN,NaN,NaN,NaN