<a href="https://colab.research.google.com/github/brunahariadni/Miniprojeto_Bruna_Analise_de_Dados_T6/blob/main/Miniprojeto_Bruna_Analise_de_Dados_T6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mini-Projeto - Análise Exploratória de Dados no Varejo

**Aluna:** Bruna Hariadni
**Turma:** Análise de Dados T6

## Objetivo

Realizar uma Análise Exploratória de Dados da base Varejo, identificando problemas de qualidade, realizando a limpeza dos dados e explorando características e padrões presentes na base.

In [1]:
# Importação e carregamento dos dados

import pandas as pd
df = pd.read_csv("Base Varejo.csv", sep=";")

In [2]:
# Visualização das cinco primeiras linhas da base

df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [3]:
# Verificação da quantidade de linhas e colunas

df.shape

(830000, 14)

In [4]:
# Verificação dos nomes das colunas

df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [5]:
# Verificação dos tipos de dados de cada coluna

df.dtypes

DATA            object
CO_ID            int64
CL_ID            int64
CL_GENERO       object
CL_EC            int64
CL_FHL           int64
CL_SEG          object
PR_ID            int64
PR_CAT          object
PR_NOME         object
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

## 2. Verificação da qualidade dos dados

Nesta etapa serão verificados possíveis problemas na base, como valores nulos, registros duplicados e inconsistências nos dados.

In [6]:
# Verificação da quantidade de valores nulos em cada coluna

df.isnull().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [7]:
# Verificação da quantidade de registros duplicados

df.duplicated().sum()

np.int64(96553)

In [8]:
# Contagem dos registros de cada categoria

df["PR_CAT"].value_counts()

PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64

In [9]:
# Visualização de alguns registros identificados como duplicados

df[df.duplicated()].head(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
51,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
77,01/02/2019,1078,290,F,1,0,B,210,ACESSORIOS,CHUPETA,NaN,NaN,NaN,NaN
78,01/02/2019,1078,290,F,1,0,B,99,LIMPEZA,DESINFETANTE,NaN,NaN,NaN,NaN
96,01/02/2019,1078,290,F,1,0,B,144,BEBIDAS,REFRIGERANTE COLA,NaN,NaN,NaN,NaN
97,01/02/2019,1078,290,F,1,0,B,125,HIGIENE,TINTURAS,NaN,NaN,NaN,NaN

## 3. Limpeza e tratamento dos dados

Nesta etapa, serão removidas colunas sem informação útil, tratados valores inconsistentes, eliminadas duplicatas e ajustados os tipos de dados necessários para a análise.

In [10]:
# Remoção das colunas completamente vazias e sem informações úteis para a análise

df = df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"])
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME'],
      dtype='object')

In [11]:
# Substituição das categorias ausentes identificadas como "#N/D, aplicação da função com .apply e verificação da contagem com o value_counts()"

def tratar_categoria(categoria):
  if categoria == "#N/D":
    return "Sem categoria"
  else:
    return categoria
df["PR_CAT"] = df["PR_CAT"].apply(tratar_categoria)
df["PR_CAT"].value_counts()

PR_CAT
ALIMENTOS        434767
HIGIENE          155574
LIMPEZA          145754
BEBIDAS           43299
PET               32399
ACESSORIOS        14557
Sem categoria      3650
Name: count, dtype: int64

In [12]:
# Armazena a quantidade de linhas antes da remoção das duplicatas

linhas_antes = len(df)

# Remove registros completamente duplicados

df = df.drop_duplicates()

# Calcula a quantidade de registros removidos

linhas_depois = len(df)
linhas_removidas = linhas_antes - linhas_depois
print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Linhas duplicadas removidas:", linhas_removidas)

Linhas antes: 830000
Linhas depois: 733447
Linhas duplicadas removidas: 96553

In [13]:
# Confirma se ainda existem registros duplicados após o tratamento

df.duplicated().sum()

np.int64(0)

In [14]:
# Verificando se o Pandas está tratando data como object/texto

df["DATA"].dtype

dtype('O')

In [15]:
# Verificando o formato visual da data

df["DATA"].head()

0    01/02/2019
1    01/02/2019
2    01/02/2019
3    01/02/2019
4    01/02/2019
Name: DATA, dtype: object

In [16]:
# Converte a coluna DATA de texto para datetime, considerando o dia na primeira posição

df["DATA"] = pd.to_datetime(df["DATA"], dayfirst=True)
df["DATA"].dtype

dtype('<M8[ns]')

In [17]:
# Verificando o novo formato da data

df["DATA"].head()

0   2019-02-01
1   2019-02-01
2   2019-02-01
3   2019-02-01
4   2019-02-01
Name: DATA, dtype: datetime64[ns]

In [18]:
# Verificação geral da estrutura e dos tipos de dados após a limpeza

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 733447 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       733447 non-null  datetime64[ns]
 1   CO_ID      733447 non-null  int64
 2   CL_ID      733447 non-null  int64
 3   CL_GENERO  733447 non-null  object
 4   CL_EC      733447 non-null  int64
 5   CL_FHL     733447 non-null  int64
 6   CL_SEG     733447 non-null  object
 7   PR_ID      733447 non-null  int64
 8   PR_CAT     733447 non-null  object
 9   PR_NOME    733447 non-null  object
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 61.6+ MB

## 4. Estatística descritiva

Nesta etapa serão analisadas estatísticas descritivas da coluna CL_FHL, que representa o número de filhos dos clientes.

In [19]:
# Verificando a quantidade de clientes que possuem 1, 2, 3 e 4 filhos / sort_index() - ordenando os números

df["CL_FHL"].value_counts().sort_index()

CL_FHL
0    384986
1     90845
2     94168
3     92407
4     71041
Name: count, dtype: int64

In [20]:
# Verificando a quantidade de IDs únicos

df["CL_ID"].nunique()

1000

In [21]:
# Cria uma base com apenas um registro por cliente

clientes = df[["CL_ID", "CL_FHL"]].drop_duplicates()

# Verifica a quantidade de clientes únicos na nova base

clientes.shape

(1000, 2)

In [22]:
# Calcula a média do número de filhos dos clientes

media = clientes["CL_FHL"].mean()

# Calcula a mediana do número de filhos dos clientes

mediana = clientes["CL_FHL"].median()

print("Média:", media)
print("Mediana:", mediana)

Média: 1.136
Mediana: 0.0

In [23]:
# Calcula a moda do número de filhos dos clientes

moda = clientes["CL_FHL"].mode()
print("Moda:", moda)

Moda: 0    0
Name: CL_FHL, dtype: int64

In [24]:
# Calcula o menor número de filhos entre os clientes

minimo = clientes["CL_FHL"].min()

# Calcula o maior número de filhos entre os clientes

maximo= clientes["CL_FHL"].max()

# Conta a quantidade de registros utilizados na análise

contagem = clientes["CL_FHL"].count()

print("Mínimo:", minimo)
print("Máximo:", maximo)
print("Contagem:", contagem)

Mínimo: 0
Máximo: 4
Contagem: 1000

In [25]:
# Calcula o desvio padrão do número de filhos dos clientes

desvio_padrao = clientes["CL_FHL"].std()
print("Desvio padrão:", round(desvio_padrao, 2))

Desvio padrão: 1.41

In [26]:
# Calcular os quartis do número de filhos dos clientes

q1 = clientes["CL_FHL"].quantile(0.25)
q2 = clientes["CL_FHL"].quantile(0.50)
q3 = clientes["CL_FHL"].quantile(0.75)

print("Q1 (25%)", q1)
print("Q2 (50%)", q2)
print("Q3 (75%)", q3)

Q1 (25%) 0.0
Q2 (50%) 0.0
Q3 (75%) 2.0

## 5. Validação do identificador de compra

Nesta etapa será analisada a coluna `CO_ID`, responsável por identificar as compras realizadas. Como cada linha da base representa um item vendido, um mesmo `CO_ID` pode aparecer em vários registros quando uma compra possui mais de um produto.

A análise tem como objetivo verificar a quantidade de compras únicas e confirmar que a repetição do `CO_ID` não representa necessariamente uma duplicidade, mas diferentes itens pertencentes à mesma compra.

In [27]:
# Verifica a quantidade de compras únicas na base

quantidade_compras = df["CO_ID"].nunique()
print("Quantidade de compras:", quantidade_compras)

Quantidade de compras: 18471

In [28]:
# Agrupa os registros pelo identificador da compra e conta quantos itens existem em cada uma

itens_por_compra = df.groupby("CO_ID").size()
itens_por_compra.head()

CO_ID
1000    46
1040    15
1078    63
1082    62
1103     6
dtype: int64

In [29]:
# Visualiza os registros associados a uma compra específica

df[df["CO_ID"] == 1000].head(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,2019-02-01,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,2019-02-01,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,2019-02-01,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,2019-02-01,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
5,2019-02-01,1000,534,M,4,1,C,187,HIGIENE,HASTES FLEXIVEIS
6,2019-02-01,1000,534,M,4,1,C,163,ALIMENTOS,MORTADELA
7,2019-02-01,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
8,2019-02-01,1000,534,M,4,1,C,95,LIMPEZA,AMACIANTE
9,2019-02-01,1000,534,M,4,1,C,198,BEBIDAS,ENERGETICO

### Validação do CO_ID

A análise confirmou que o `CO_ID` identifica uma compra e pode aparecer em vários registros, pois cada linha da base representa um item associado à compra. Foram identificadas 18.471 compras únicas.

Por exemplo, o `CO_ID 1000` possui 46 registros associados, contendo diferentes produtos. Portanto, a repetição do `CO_ID` não deve ser considerada uma duplicidade por si só.

## 6. Agrupamento e análise dos dados

Nesta etapa serão realizados agrupamentos para analisar os dados de diferentes perspectivas. O objetivo é resumir informações da base e identificar padrões relacionados às compras, aos clientes e aos produtos.

In [30]:
# Agrupa os registros por gênero e conta a quantidade de compras únicas

compras_por_genero = df.groupby("CL_GENERO")["CO_ID"].nunique()
print(compras_por_genero)

CL_GENERO
F    9615
M    8856
Name: CO_ID, dtype: int64

In [31]:
# Agrupa os registros por categoria, conta a quantidade de itens e ordena o resultado do maior para o menor

itens_por_categoria = df.groupby("PR_CAT").size().sort_values(ascending=False)

print(itens_por_categoria)

PR_CAT
ALIMENTOS        384197
HIGIENE          137702
LIMPEZA          128632
BEBIDAS           38264
PET               28553
ACESSORIOS        12871
Sem categoria      3228
dtype: int64

In [32]:
# Agrupa os registros por gênero e compara compras e clientes únicos

compras_por_genero = df.groupby("CL_GENERO")["CO_ID"].nunique()
clientes_por_genero = df.groupby("CL_GENERO")["CL_ID"].nunique()

print("Compras por gênero:")
print(compras_por_genero)

print("\nClientes por gênero:")
print(clientes_por_genero)

Compras por gênero:
CL_GENERO
F    9615
M    8856
Name: CO_ID, dtype: int64

Clientes por gênero:
CL_GENERO
F    519
M    481
Name: CL_ID, dtype: int64

In [33]:
# Calcula a média de compras por cliente em cada gênero

media_compras_por_cliente = round(compras_por_genero / clientes_por_genero, 2)
print("Média de compras por cliente:")
print(media_compras_por_cliente)

Média de compras por cliente:
CL_GENERO
F    18.53
M    18.41
dtype: float64

## 7. Exportação da base tratada

Após as etapas de limpeza, validação e transformação dos dados, a base tratada será exportada para um novo arquivo CSV, preservando os dados originais e permitindo o uso posterior da versão limpa.

In [34]:
# Exporta a base tratada para um novo arquivo CSV

df.to_csv("df_limpo.csv", sep=";", index=False)

## 8. Conclusões e insights

Após a limpeza, validação e análise dos dados, foi possível identificar alguns padrões e características relevantes da base de varejo.

### Principais insights

- A categoria **ALIMENTOS** apresentou a maior quantidade de registros de itens, com 384.197 ocorrências, ficando bem acima das demais categorias.

- Foram identificadas **18.471 compras únicas** na base. A repetição do `CO_ID` é esperada, pois uma mesma compra pode possuir vários itens associados.

- O gênero feminino apresentou maior quantidade total de compras, com **9.615 compras**, enquanto o masculino apresentou **8.856**. Entretanto, também existem mais clientes do gênero feminino na base.

- Ao considerar a média de compras por cliente, os dois gêneros apresentaram resultados muito próximos: aproximadamente **18,53 compras por cliente no gênero feminino** e **18,41 no masculino**, indicando comportamento de frequência de compra semelhante entre os grupos.

- Em relação ao número de filhos, a média foi de aproximadamente **1,14 filho por cliente**, enquanto a mediana e a moda foram iguais a 0. Além disso, 75% dos clientes possuem até 2 filhos, indicando maior concentração nos valores mais baixos.

- Durante a etapa de limpeza foram encontrados registros duplicados, colunas completamente vazias e 3.228 registros de produtos sem categoria definida. Esses problemas reforçam a importância do tratamento e da validação dos dados antes da realização das análises.